var dan_toc = [
    {dt: "Kinh"},
    {dt: "Tày"},
    {dt: "Thái"},
    {dt: "Thổ"},
    {dt: "Mường"},
    {dt: "Chăm"},
    {dt: "Ê Đê"},
    {dt: "Khơ me"},
    {dt: "Khơ Mú"},
    {dt: "Ba Na"},
    {dt: "Bố Y"},
    {dt: "Brâu"},
    {dt: "Nùng"},
    {dt: "Tà Ôi"},
    {dt: "H'Mông"},
    {dt: "Sán Dìu"},
    {dt: "M'Nông"},
    {dt: "Bru"},
    {dt: "Xtiêng"},
    {dt: "La Hủ"},
    {dt: "Dao"},
    {dt: "Mạ"},
    {dt: "Si La"},
    {dt: "Ngái"},
    {dt: "Cơ Tu"},
    {dt: "Hariêng"},
    {dt: "La Ha"},
    {dt: "Lào"},
    {dt: "Rơ Măm"},
    {dt: "Gié - TLa"},
    {dt: "Xơ Đăng"},
    {dt: "Lô Lô"},
    {dt: "Sán Chay"},
    {dt: "Kháng"},
    {dt: "Cơ Ho"},
    {dt: "Lự"},
    {dt: "Cơ Lao"},
    {dt: "Ra Glai"},
    {dt: "Giáy"},
    {dt: "Hrê"},
    {dt: "Cống"},
    {dt: "Phù Lá"},
    {dt: "Chu ru"},
    {dt: "Pu Péo"},
    {dt: "Pà Thẻn"},
    {dt: "Chứt"},
    {dt: "Ô đu"},
    {dt: "Hà Nhì"},
    {dt: "Co"},
    {dt: "Hoa"},
    {dt: "Mảng"},
    {dt: "Chơ Ro"},
    {dt: "Gia Lai"},
    {dt: "La Chí"}
]
module.exports = dan_toc;